/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import javax.swing.JOptionPane;

/**
 *
 * @author Raquel
 */
public class JFrameArea extends javax.swing.JFrame {

    /**
     * Creates new form JFrameArea
     */
    public JFrameArea() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFondo = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        area = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jTextFieldBase = new javax.swing.JTextField();
        calcularBoton = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCerrar.setBackground(new java.awt.Color(105, 181, 255));
        botonCerrar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrar.setText("Cerrar");
        botonCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 60, 20));

        area.setBackground(new java.awt.Color(255, 255, 255));
        area.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setText("Introduzca una altura: ");
        getContentPane().add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 30));

        base.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        base.setForeground(new java.awt.Color(255, 255, 255));
        base.setText("Introduzca una base:");
        getContentPane().add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("BIENVENIDO A CÁLCULO MATEMÁTICO");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 480, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoPrograma .png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jTextFieldAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlturaActionPerformed(evt);
            }
        });
        jTextFieldAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlturaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 30));

        jTextFieldBase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBaseActionPerformed(evt);
            }
        });
        jTextFieldBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBaseKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 153, 200, 30));

        calcularBoton.setBackground(new java.awt.Color(46, 166, 232));
        calcularBoton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calcularBoton.setForeground(new java.awt.Color(255, 255, 255));
        calcularBoton.setText("CALCULAR ÁREA ");
        calcularBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBotonActionPerformed(evt);
            }
        });
        getContentPane().add(calcularBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 200, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void jTextFieldAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlturaActionPerformed

    private void jTextFieldBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBaseActionPerformed

    private void jTextFieldBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBaseKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_jTextFieldBaseKeyTyped

    private void jTextFieldAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlturaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_jTextFieldAlturaKeyTyped

    private void calcularBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBotonActionPerformed
        // TODO add your handling code here:
        String altura = this.jTextFieldAltura.getText();
        String base = this.jTextFieldBase.getText();
        if(altura.length()==0 || base.length() == 0){
          JOptionPane.showMessageDialog(null, "Introduce un valor", "Resultado", JOptionPane.PLAIN_MESSAGE);
        }
        int alturaCovert = Integer.parseInt(altura);   
        int baseConvert = Integer.parseInt(base);
        
        
        int area = alturaCovert * baseConvert;
        System.out.println("Resultado: " + area);
        
           JOptionPane.showMessageDialog(null, "El area es: " + area , "Resultado", JOptionPane.PLAIN_MESSAGE);
               
        
       
    }//GEN-LAST:event_calcularBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel area;
    private javax.swing.JLabel base;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton calcularBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldBase;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
